---
title: "Nakajima NAR 2021 - scRNA-seq analysis"
author: "Eijy Nagai"
date: "2023-03-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download the data at GEO
In the KI_UT_class: find data/ directory
Search in Google: “GSE144623” and “GEO”
If you cannot find in the original paper:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144623
Download and extract the data into the directory datasets/   


## Install and load necessary packages
```{r}
# mask require, check and download if not installed
require2 <- function(x) { 
  if (!base::require(x, character.only = TRUE)) {
    install.packages(x, dep = TRUE) ; 
    base::require(x, character.only = TRUE)
    } 
  base::library(x, character.only = TRUE)
  #do.call("library", list(x))
  }
require2("Seurat")
require2("tidyverse")
require2("patchwork")
#install.packages("qqconf")
#require2("metap")
#require2("BiocManager")
#BiocManager::install("dittoSeq", update = FALSE)
```



```{r}
ct_path <- "datasets/nakajima/GSM4292484_filtered_gene_bc_matrices_P10.csv.gz"
ct_matrix <- read.csv(file = ct_path, header = TRUE)
```

```{r}
#head(ct_matrix)
```

```{r}
rownames(ct_matrix) <- ct_matrix[[1]]
ct_matrix[[1]] <- NULL
#head(ct_matrix)
```


```{r}
ct_matrix <- as(as.matrix(ct_matrix), "sparseMatrix")
#head(ct_matrix)
```


```{r}
ct <- CreateSeuratObject(counts = ct_matrix, project = "gbm")
ct$stim <- "0h"
```

```{r}
head(ct@meta.data)
```

```{r}
# Same thing for the second dataset

tr_path <- "datasets/nakajima/GSM4292485_filtered_gene_bc_matrices_12h.csv.gz"
tr_matrix <- read.csv(file = ct_path, header = TRUE)

rownames(tr_matrix) <- tr_matrix[[1]]
tr_matrix[[1]] <- NULL

tr <- CreateSeuratObject(counts = tr_matrix, project = "gbm")
tr$stim <- "12h"
```
```{r}
so.list <- c(ct, tr)
so.list
```


```{r}
so.list <- lapply(X = so.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
```

```{r}
so.anchors <- FindIntegrationAnchors(object.list = so.list, dims = 1:20)
```

```{r}
so.combined <- IntegrateData(anchorset = so.anchors, dims = 1:20)
```

```{r}
DefaultAssay(so.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
so.combined <- ScaleData(so.combined, verbose = FALSE)
so.combined <- RunPCA(so.combined, npcs = 30, verbose = FALSE)
# t-SNE and Clustering
so.combined <- RunUMAP(so.combined, reduction = "pca", dims = 1:20)
so.combined <- FindNeighbors(so.combined, reduction = "pca", dims = 1:20)
so.combined <- FindClusters(so.combined, resolution = 0.5)
```


```{r}
# Visualization
p1 <- DimPlot(so.combined, reduction = "umap", group.by = "stim")
p2 <- DimPlot(so.combined, reduction = "umap", label = TRUE)
p1 + p2
```


```{r}
DimPlot(so.combined, reduction = "umap", split.by = "stim")
```


